### ISSUE TITLE
Passing value to nodeSlector parameter of helm chart via set.

### ISSUE THREAD

**Issue by aigdev** [lablabs/terraform-aws-eks-alb-ingress#11]
Hi,

I have an issue with passing value to nodeSelector parameter of helm chart via set.

I tried to pass like this:

```
set {
    name  = "nodeSelector.node-role\\.kubernetes\\.io/infra"
    value = "true"
  } 
```

But I have a syntax issue converting to yaml:

`Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadString: expects " or n, but found t, error found in #10 byte of ...|o/infra":true...`

Also I tried to deploy helm chart itself without TF with setting nodeSelector parameter, as mentioned on [:](https://helm.sh/docs/intro/using_helm/) but I also have the same issue.

`--set nodeSelector."node-role\.kubernetes\.io/infra"=true `

Could you please advise how it can be implemented.

Thanks a lot!

**Comment by dojci** [comment]
ALB ingress controller is deprecated, plase use https://github.com/lablabs/terraform-aws-eks-load-balancer-controller instead.
