### ISSUE TITLE
the example wont attach the subnets 

### ISSUE THREAD

**Issue by sivarita** [lablabs/terraform-aws-eks-alb-ingress#12]
when i try to deploy the 2048 example of amazon using the example i get this

`kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to retrieval of subnets failed to resolve 2 qualified subnets. Subnets must contain the kubernetes.io/cluster/\u003ccluster name\u003e tag with a value of shared or owned and the kubernetes.io/role/elb tag signifying it should be used for ALBs Additionally, there must be at least 2 subnets with unique availability zones as required by ALBs. Either tag subnets to meet this requirement or use the subnets annotation on the ingress resource to explicitly call out what subnets to use for ALB creation. The subnets that did resolve were []"  "controller"="alb-ingress-controller" "request"={"Namespace":"game-2048","Name":"ingress-2048"`

clarification, I only use until alb_ingress of the example, the rest I raise it with ingress of amazon

**Comment by dojci** [comment]
@sivarita it seems that you have not properly setup tags in your vpc for EKS or the subnets annotation on the ingress resource. Please see:
1.  `Subnet tagging requirement` section https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html
2. ingress resource tags https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/ingress/annotations.md#subnets.
