### ISSUE TITLE
Support Terraform 0.14.x

### ISSUE THREAD

**Issue by whume** [lablabs/terraform-aws-eks-alb-ingress#13]
I think I am hitting this bug in the modules due to the use of the dynamic providers but I cannot test to confirm since the modules do not support Terraform 0.14. Can we add support for that?

hashicorp/terraform-provider-helm#476

**Comment by haad** [comment]
Sure if we are open to merge any PR TF 0.14 if you have any time on your hands. Just make sure you bump major version.

**Comment by dojci** [comment]
ALB ingress controller is deprecated, plase use https://github.com/lablabs/terraform-aws-eks-load-balancer-controller instead.
